### ISSUE TITLE
Patch SciPy?

### ISSUE THREAD

**Issue by JensRantil** [olivierverdier/newton#1]
Hello Olivier!

Just curious, isn't this something that should be contributed back to the SciPy project if their solver can't handle certain cases?

/J

**Comment by olivierverdier** [comment]
Hi Jens,
No, this package does almost nothing, it's only useful for debugging purposes, for instance when the Jacobian happens to be singular, the solver falls back to the manual method and you can inspect its eigenvectors, for instance. Thanks for your interest!! :-)

**Comment by JensRantil** [comment]
Ah, I see! :+1:
